apiVersion: batch/v1
kind: CronJob
metadata:
  name: example-cronjob
spec:
  schedule: "*/5 * * * *"  # Every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob-task
              image: busybox
              command: ["echo", "Running scheduled task"]
          restartPolicy: Never
