apiVersion: v1
kind: Service
metadata:
  name: my-headless-service
spec:
  clusterIP: None  # Makes it headless
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
