apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
    - name: my-container
      image: my-app-image
      ports:
        - containerPort: 8080
      livenessProbe:  # Checks if the app is running
        httpGet:
          path: /health
          port: 8080
        initialDelaySeconds: 3
        periodSeconds: 10
      readinessProbe:  # Checks if the app is ready to receive traffic
        httpGet:
          path: /ready
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5
