apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-fast-pvc
spec:
  storageClassName: fast-storage  # Use the "fast-storage" class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi